spring.application.name: hanghae-architecture
spring.profiles.active: local

spring:
  config:
    import:
      - db-core.yml

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: local



